import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " p-4"}>
        <div>
          <Link href="/" className="mr-3 hover:underline">
            Home
          </Link>
          <Link href="/users" className="hover:underline">
            Users
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
